// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrol9-t1NOmNKoK6JZM29DOO5l0rhYeE',
    appId: '1:607897064853:web:6d14b624ce3a159a74d29c',
    messagingSenderId: '607897064853',
    projectId: 'login-flutter-21455',
    authDomain: 'login-flutter-21455.firebaseapp.com',
    storageBucket: 'login-flutter-21455.appspot.com',
    measurementId: 'G-S8VKD721XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MEj9Kf8-ZsGZxopLIhFtFpjzaKvpKFM',
    appId: '1:607897064853:android:7dbefdb76059a5bf74d29c',
    messagingSenderId: '607897064853',
    projectId: 'login-flutter-21455',
    storageBucket: 'login-flutter-21455.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquZ9zTfwNdq0P-9gIFzppikpcmqhB0I4',
    appId: '1:607897064853:ios:bb75301b2192157274d29c',
    messagingSenderId: '607897064853',
    projectId: 'login-flutter-21455',
    storageBucket: 'login-flutter-21455.appspot.com',
    iosBundleId: 'com.example.firebasesignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrol9-t1NOmNKoK6JZM29DOO5l0rhYeE',
    appId: '1:607897064853:web:023545436880741374d29c',
    messagingSenderId: '607897064853',
    projectId: 'login-flutter-21455',
    authDomain: 'login-flutter-21455.firebaseapp.com',
    storageBucket: 'login-flutter-21455.appspot.com',
    measurementId: 'G-DDN2481TN6',
  );
}
